files:
  - source: /i18n/en-US/*.json
    translation: /i18n/%locale%/%original_file_name%
  - source: /i18n/en-US/admin/*.json
    translation: /i18n/%locale%/admin/%original_file_name%
  - source: /i18n/en-US/config/*.json
    translation: /i18n/%locale%/config/%original_file_name%
  - source: /i18n/en-US/core/*.json
    translation: /i18n/%locale%/core/%original_file_name%
- name: Deploy to Heroku
  uses: AkhileshNS/heroku-deploy@v3.0.4
  with:
    # This will be used for authentication. You can find it in your heroku homepage account settings
    heroku_api_key: 
    # Email that you use with heroku
    heroku_email: 
    # The appname to use for deploying/updating
    heroku_app_name: 
    # An optional buildpack to use when creating the heroku application
    buildpack: # optional
    # The branch that you would like to deploy to Heroku
    branch: # optional, default is HEAD
    # Set this to true if you don't want to use --force when switching branches
    dontuseforce: # optional
    # Will deploy using Dockerfile in project root.
    usedocker: # optional
    # Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled
    docker_heroku_process_type: # optional, default is web
    # Set if your app is located in a subdirectory.
    appdir: # optional, default is 
